"""empty message

Revision ID: 2d45b2f5c2c4
Revises: cc9489cf5029
Create Date: 2019-09-18 19:06:22.822801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d45b2f5c2c4'
down_revision = 'cc9489cf5029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('photo', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'photo')
    # ### end Alembic commands ###
