"""empty message

Revision ID: ef44c4300345
Revises: 5a7fc6df6e7c
Create Date: 2019-09-14 18:10:24.200765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef44c4300345'
down_revision = '5a7fc6df6e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'type',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'product', 'type', ['type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.alter_column('product', 'type',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
